src/Entity/Avis.php
<?php

namespace App\Entity;

use App\Repository\AvisRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AvisRepository::class)]
class Avis
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $commentaire = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_creation = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $note = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'avis')]
    private ?Livre $livre = null;

    #[ORM\Column(type: Types::BOOLEAN, options: ["default" => true])]
    private bool $statut = true;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(string $commentaire): static
    {
        $this->commentaire = $commentaire;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): static
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    public function getNote(): ?int
    {
        return $this->note;
    }

    public function setNote(int $note): static
    {
        $this->note = $note;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    public function getLivre(): ?Livre
    {
        return $this->livre;
    }

    public function setLivre(?Livre $livre): static
    {
        $this->livre = $livre;

        return $this;
    }

    public function isStatut(): ?bool
    {
        return $this->statut;
    }

    public function setStatut(bool $statut): static
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Form/AvisType.php
<?php

namespace App\Form;

use App\Entity\Avis;
use App\Entity\Livre;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AvisType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('commentaire')
            ->add('date_creation')
            ->add('note')
            ->add('statut')
            ->add('user', EntityType::class, [
                'class' => User::class,
'choice_label' => 'id',
            ])
            ->add('livre', EntityType::class, [
                'class' => Livre::class,
'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Avis::class,
        ]);
    }
}

src/Controller/AvisController.php
<?php

namespace App\Controller;

use App\Entity\Avis;
use App\Form\AvisType;
use App\Repository\AvisRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/avis')]
class AvisController extends AbstractController
{
    #[Route('/', name: 'app_avis_index', methods: ['GET'])]
    public function index(AvisRepository $avisRepository): Response
    {
        return $this->render('avis/index.html.twig', [
            'avis' => $avisRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_avis_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $avi = new Avis();
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avi);
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/new.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_show', methods: ['GET'])]
    public function show(Avis $avi): Response
    {
        return $this->render('avis/show.html.twig', [
            'avi' => $avi,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_avis_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(AvisType::class, $avi);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('avis/edit.html.twig', [
            'avi' => $avi,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_avis_delete', methods: ['POST'])]
    public function delete(Request $request, Avis $avi, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$avi->getId(), $request->request->get('_token'))) {
            $entityManager->remove($avi);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_avis_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/avis/_delete_form.html.twig
<form method="post" action="{{ path('app_avis_delete', {'id': avi.id}) }}" onsubmit="return confirm('Etes-vous sûr de vouloir supprimer la catégorie ?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ avi.id) }}">
    <button class="btn">Supprimer</button>
</form>

templates/avis/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/avis/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Avis{% endblock %}

{% block body %}
    <h1>Edit Avis</h1>

    {{ include('avis/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_avis_index') }}">Retourner à la liste</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}

templates/avis/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis index{% endblock %}

{% block body %}
    <h1>Liste des avis</h1>

    <p>Vous pouvez cacher les avis créé par les utilisateurs</p>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Commentaire</th>
                <th>Date_creation</th>
                <th>Note</th>
                <th>Statut</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for avi in avis %}
            <tr>
                <td>{{ avi.id }}</td>
                <td>{{ avi.commentaire }}</td>
                <td>{{ avi.dateCreation ? avi.dateCreation|date('Y-m-d') : '' }}</td>
                <td>{{ avi.note }}</td>
                <td>{{ avi.statut ? 'Yes' : 'No' }}</td>
                <td>
                    <a href="{{ path('app_avis_show', {'id': avi.id}) }}">Montrer</a>
                    <a href="{{ path('app_avis_edit', {'id': avi.id}) }}">Modifier</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">Non trouvé</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/avis/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Avis{% endblock %}

{% block body %}
    <h1>Create new Avis</h1>

    {{ include('avis/_form.html.twig') }}

    <a href="{{ path('app_avis_index') }}">Retourner à la liste</a>
{% endblock %}

templates/avis/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Avis{% endblock %}

{% block body %}
    <h1>Avis</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ avi.id }}</td>
            </tr>
            <tr>
                <th>Commentaire</th>
                <td>{{ avi.commentaire }}</td>
            </tr>
            <tr>
                <th>Date_creation</th>
                <td>{{ avi.dateCreation ? avi.dateCreation|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ avi.note }}</td>
            </tr>
            <tr>
                <th>Statut</th>
                <td>{{ avi.statut ? 'Yes' : 'No' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_avis_index') }}">Retourner à la liste</a>

    <a href="{{ path('app_avis_edit', {'id': avi.id}) }}">edit</a>

    {{ include('avis/_delete_form.html.twig') }}
{% endblock %}