src/Entity/Livre.php
<?php

namespace App\Entity;

use App\Repository\LivreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: LivreRepository::class)]
class Livre
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $titre = null;

    #[ORM\Column(length: 255)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $date_parution = null;

    #[ORM\ManyToMany(targetEntity: Categorie::class, mappedBy: 'livres')]
    private Collection $categories;

    #[ORM\OneToMany(targetEntity: Avis::class, mappedBy: 'livre')]
    private Collection $avis;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->avis = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): static
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getDateParution(): ?\DateTimeInterface
    {
        return $this->date_parution;
    }

    public function setDateParution(\DateTimeInterface $date_parution): static
    {
        $this->date_parution = $date_parution;

        return $this;
    }

    /**
     * @return Collection<int, Categorie>
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Categorie $category): static
    {
        if (!$this->categories->contains($category)) {
            $this->categories->add($category);
            $category->addLivre($this);
        }

        return $this;
    }

    public function removeCategory(Categorie $category): static
    {
        if ($this->categories->removeElement($category)) {
            $category->removeLivre($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setLivre($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getLivre() === $this) {
                $avi->setLivre(null);
            }
        }

        return $this;
    }
}

src/Controller/DashboardController.php
<?php

namespace App\Controller;

use App\Entity\Livre;
use App\Entity\Avis;
use App\Entity\User;
use App\Form\AvisType;
use App\Repository\LivreRepository;
use App\Repository\AvisRepository;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class DashboardController extends AbstractController
{
    #[Route('/', name: 'app_dashboard')]
	public function index(LivreRepository $livreRepository): Response
	{
		return $this->render('dashboard/index.html.twig', [
			'controller_name' => 'DashboardController',
			'livres' => $livreRepository->findAll(),
		]);
	}

	#[Route('/Livre/{id}', name: 'app_livre_for_user', methods: ['GET'])]
	public function show_livre(Livre $livre, AvisRepository $avisRepository): Response
	{
		$avis = $livre->getAvis();
		
		return $this->render('dashboard/livre_for_user.html.twig', [
			'livre' => $livre,
			'avis' => $avis,
		]);
	}

    #[Route('/new/{livreId}/{userId}', name: 'app_ajouter_avis', methods: ['GET', 'POST'])]
    public function add_avis(int $livreId, int $userId, Request $request, EntityManagerInterface $entityManager, LivreRepository $livreRepository, UserRepository $userRepository): Response
    {
        $livre = $livreRepository->find($livreId);
        
        $user = $userRepository->find($userId);
    
        $avis = new Avis();
        $avis->setLivre($livre);
        $avis->setUser($user); 
    
        $form = $this->createForm(AvisType::class, $avis);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($avis);
            $entityManager->flush();
    
            return $this->redirectToRoute('app_dashboard');
        }
    
        return $this->render('dashboard/ajouter_avis.html.twig', [
            'form' => $form->createView(),
        ]);
    }

}

templates/dashboard/ajouter_avis.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un avis{% endblock %}

{% block body %}
    <h1>Ajouter un avis</h1>

    {{ form_start(form) }}
        {{ form_row(form.commentaire) }}
        {{ form_row(form.note) }}

        {{ form_widget(form.livre, {'attr': {'hidden': 'hidden'}}) }}

        {{ form_widget(form.user, {'attr': {'hidden': 'hidden'}}) }}
    
        {{ form_row(form.statut, {'attr': {'hidden': 'hidden'}}) }}

        <button type="submit" class="btn btn-primary">Ajouter</button>
    {{ form_end(form) }}
{% endblock %}

templates/dashboard/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Hello!
{% endblock %}

{% block body %}

    <div class="example-wrapper">
        <h1>
        Bienvenue {% if app.user%} {{app.user.email}} {% endif %}
        </h1>

    <h3>Liste des livres</h3>

        <table class="table">
            <thead>
                <tr>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Date de parution</th>
                    <th>Catégories</th>
                </tr>
            </thead>
            <tbody>
            {% for livre in livres %}
                <tr>
                    <td><a href="{{ path('app_livre_for_user', { id: livre.id }) }}">{{ livre.titre }}</a></td>
                    <td>{{ livre.description }}</td>
                    <td>{{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</td>
                    <td>
                        {% for categories in livre.getCategories() %}
                            {{ categories.getStyle() }}
                            <br />
                        {% endfor %}
                        </td>
                </tr>
            {% else %}
                <tr>
                    <td colspan="5">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}
                

templates/dashboard/livre_for_user.html.twig
{% extends 'base.html.twig' %}

{% block title %}Livre{% endblock %}

{% block body %}
    <h1>{{ livre.titre }}</h1>
    <h4>Sorti le {{ livre.dateParution ? livre.dateParution|date('Y-m-d') : '' }}</h4>

    <p>{{ livre.description }}</p>

    <table class="table">
        <tbody>
            <tr>
                <th>Catégories </th>
                <td>- {% for categories in livre.getCategories() %}
                {{ categories.getStyle() }} -  
                {% endfor %}</td>
            </tr>
        </tbody>
    </table>

<h2>Avis :</h2>

    {% if app.user %}
        <p><a href="{{ path('app_ajouter_avis', {'livreId': livre.id, 'userId': app.user.id}) }}">Ajouter un avis</a></p>
    {% else %}
        <p>Vous avez besoin d'être <a href="{{ path('app_login') }}"> connecté </a>pour laisser un avis</p>
    {% endif %}
    <ul>
        {% for avi in avis %}
        {% if avi.isStatut()==1 %}
            <li>
                <strong>{{ avi.getUser().getEmail() }}</strong> - Note: {{ avi.note }}/5 - {{ avi.commentaire }}
               
            </li> {% endif %}
        {% endfor %}
    </ul>

    <a href="{{ path('app_dashboard') }}">Retour à la page d'accueil</a>
{% endblock %}

templates/dashboard/profil_user.html.twig
à voir après